- discord/interactions/index.ts
- discord/interactions/viewConfig.ts
- discord/slashCommands.ts
> feat: view config command

- config.ts
- cron.ts
- db/data-source.ts
- db/entity/AddressToRefresh.ts
- db/index.ts
- db/migration/1698497523001-addingAddressToRefresh.ts
- indexer/indexer.ts
- indexer/networks.json
- starkscan/retrieveAssets.ts
- starkyModules/erc721.ts
- starkyModules/erc721Metadata.ts
- starkyModules/types.ts
- starkyModules/walletDetector.ts
Fixing stability issues (fixing memory crashes, improving indexer speed, ensuring every block was processed before validating the chunk in the db)
> fix: stability issues

- cron.ts
- indexer/indexer.ts
- pages/api/verify.ts
- improvings logs
- fixing the user refresh when connecting a wallet 
- improving indexer stability
> feat: logs improvements

- cron.ts
- db/entity/DiscordServerConfig.ts
- indexer/blockStack.ts
- indexer/indexer.ts
- starkscan/retrieveAssets.ts
- starkyModules/erc721.ts
- starkyModules/erc721Metadata.ts
- starkyModules/index.ts
- starkyModules/walletDetector.ts
- types/starkyModules.ts
As on one single server, multiple configs share the same contract address, we don't want to fetch for each user multiple times the same assets
> feat: optimisation

- cron.ts
- discord/interactions/debugUser.ts
- discord/interactions/index.ts
- discord/interactions/permissions.ts
- discord/interactions/refreshCommand.ts
- discord/interactions/viewConfig.ts
- discord/slashCommands.ts
- pages/api/verify.ts
- utils/preLoadMemberAssets.ts
> feat: debug command

- README.md
adding /starky-refresh, /starky-view-config, /starky-debug-user, /starky-set-config-custom-api in the readme file
> readme: adding new commands

- discord/interactions/viewConfig.ts
Now showing other module config fields such as customApiUri or customApiParamName
> feat: improving view-config ocmmand

- Dockerfile
- docker-entrypoint.sh
- indexer/indexer.ts
- indexer/stream.ts
Allowing bigger messages from Apibara's indexers. As a consequence, we add an optional swap file to the container if needed (useful for small VPS with low RAM, as Apibara can send very big messages)
> fix: max message length for indexers

- configs/chainAliasByNetwork.json
- package-lock.json
- package.json
- pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
- starkyModules/erc721.ts
- utils/starknet/call.ts
- yarn.lock
Fixes deprecation issues with the Starknet's API
> feat: updating starknet lib

- pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
- utils/starknet/verifySignature.ts
> fix: uninitialized contract error message not being shown

- pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
- styles/Verify.module.scss
Adding more advanced information so that we can help users more easily
> feat: improving error messages

- pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
Sometimes disonnect for no reason while signing messsage
> fix: wallet handler

- pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
- utils/starknet/verifySignature.ts
> feat: support more interfaces

- indexer/indexer.ts
> Fix: Only launch indexers for networks with indexer === true

- server.ts
resolves #60 
Changes :
- Removed the todo comment from the launchServer function
> Fix: Remove outdated TODO comment for HTTPS handling

- configs/networks.json
- cron.ts
- discord/client.ts
- discord/index.ts
- discord/interactions/connectCommand.ts
- discord/interactions/index.ts
- discord/slashCommands.ts
- indexer/processBlocks.ts
- package-lock.json
- pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
- server.ts
- starkyModules/walletDetector.ts
- utils/discord/logs.ts
- utils/discord/refreshRoles.ts
- utils/retrieveAsset.ts
- utils/starkscan/retrieveAssetsFromStarkscan.ts
- utils/starkscan/retrieveTx.ts
- watchTower.ts
- yarn.lock
> Fix: Implement WatchTower logging module to replace console.log

- configs/networks.json
> Add a new indexer boolean field

- .env.local.sample
- config.ts
- indexer/indexer.ts
- indexer/processBlocks.ts
> Fix: Log one block out of x blocks based on LOG_EVERY_X_BLOCK env variable

- README.md
close: #80 
Added LOG_EVERY_X_BLOCK to environment variables in README
> Docs: Add LOG_EVERY_X_BLOCK to environment variables in README

- discord/interactions/addConfigCommand.ts
- discord/interactions/index.ts
> Fix: Add back button navigation to config command

- discord/interactions/index.ts
- discord/interactions/listConfigs.ts
- discord/slashCommands.ts
> Feature: Implement /list-configs command to display existing configurations

- discord/utils.ts
- pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
- styles/Verify.module.scss
Closes #91 
Proof:
@Marchand-Nicolas Kindly review
> Fix: Display Discord server icon next to server name

- configs/networks.json
- discord/interactions/connectCommand.ts
> Fix: Use label field in network dropdown in connectCommand.ts

- db/entity/DiscordMember.ts
- discord/interactions/connectCommand.ts
- discord/interactions/index.ts
> Fix: Display reconnect buttons and update multi-network support

- .eslintrc.json
- db/data-source.ts
- db/entity/DiscordAnalyticsToken.ts
- db/entity/DiscordMember.ts
- db/entity/DiscordServer.ts
- db/entity/DiscordServerConfig.ts
- db/index.ts
- db/migration/1742312632510-CreateDiscordAnalyticsTokenTable.ts
- discord/interactions/handleAnalyticsCommand.ts
- discord/slashCommands.ts
- package-lock.json
- package.json
- pages/analytics/[guildId]/[tokenId].tsx
- utils/database.ts
- utils/validateToken.ts
This PR implements security checks for the analytics page by validating tokens against the database.
*Changes Implemented* 🛠️
1. **Token Validation Logic**  
- Added `validateToken` utility function to check token validity/expiry  
- Integrated validation in `getServerSideProps` of `analytics/[guildId]/[tokenId].tsx`  
- Redirects to homepage for invalid/expired tokens  
2. **Database Updates**  
- Created new migration for `discord_analytics_token` table  
```sql
CREATE TABLE "discord_analytics_token";
3. **Security Improvements**
- Added automatic cleanup of expired tokens during validation
- Used UTC timestamps for consistent expiry checks
4. **Testing Performed** ✅
Generated new tokens via /starky-analytics Discord command to Verified:
- Valid tokens load the analytics page
- …
```
> Fix: Implement token validation for analytics page access

- .gitignore
- config.ts
- pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
close: #128 
reduced address length on mobile
> implementation of shortened address on mobile  view 

- pages/index.tsx
- styles/Home.module.scss
> Fix: Add triangle-prefixed help links to homepage

- pages/verify/[discordServerId]/[discordMemberId]/[customLink].tsx
- styles/Verify.module.scss
Closes #134 
Please let me know if further changes are needed! Glad to be first time contributing to starky.
> Fix: Add 'Report on Telegram' button to signature error message

- README.md
- discord/interactions/addConfigCommand.ts
- starkyModules/erc20.ts
- starkyModules/index.ts
This PR adds support for ERC-20 token gating in Starky. Users can now gate Discord roles based on a minimum ERC-20 token balance.
- Added a new `erc20.ts` module that implements token gating based on a minimum ERC-20 token balance
- Updated `starkyModules/index.ts` to include the new ERC-20 module
- Updated `README.md` documentation to mention the ERC-20 functionality alongside existing modules
The ERC-20 module follows the same pattern as existing modules but:
- Asks admins to specify a minimum token balance when configuring
- Checks if a user's wallet has at least that balance of tokens
- Supports cached balance data for performance
- Refreshes on token transfers to keep roles up to date
Tested with various token balances to ensure proper role assignment/removal.
Closes #211
> feat: added ERC20 support

- pages/dashboard/[guildId]/[tokenId].tsx
- utils/database.ts
- utils/validateDashboardToken.ts
close: #185 
✅ Summary
This PR implements token validation logic on the dashboard/[guildId]/[tokenId] page to ensure consistent behaviour with the analytics page.
🛠️ Changes Implemented
Imported and used validateToken in getServerSideProps
Handled invalid or expired tokens by rendering the same <RedirectMessage /> component as the analytics page
Ensured consistent error handling across both pages
📋 Notes
Reused the same UI and message for token expiration to ensure consistency
Minor update to error handling for better user feedback
> Fix: Add token validity check to dashboard/[guildId]/[tokenId].tsx
